### ISSUE TITLE
ammeter breaks RSpec's built-in `exist` matcher

### ISSUE THREAD

**Issue by tragiclifestories** [alexrothenberg/ammeter#60]
Example app demonstrating the problem [here](https://github.com/tragiclifestories/ammeter-problem). 

RSpec has a matcher built in that just calls the `exist?` or `exists?` method on the subject and passes if it returns true (or truthy I guess). requiring `ammeter/init` clobbers that matcher and breaks any tests that rely on the default RSpec behaviour.

**Comment by pyromaniackeca** [comment]
Is this still an issue?

**Comment by cflipse** [comment]
yes

**Comment by tragiclifestories** [comment]
I'd completely forgotten about this 😅 I bumped the link reproduction to the latest RSpec and ammeter and the error still occurs.

**Comment by redferret** [comment]
Is there any alternative gem for testing generators?

**Comment by redferret** [comment]
I suggest pulling this gem down and just re naming the matcher.
The `exist` matcher needs to be renamed to fix the issue.

**Comment by pirj** [comment]
This loud deprecation broke RSpec's [own CI](https://github.com/rspec/rspec-core/actions/runs/7065084585/job/19234403087?pr=3054), which is kept warning-free.

It turned out funny that rspec-rails's specs were relying on the Ammeter's implementation of the `exist` matcher.
```
     Failure/Error: expect(generator_spec).to exist
       expected "/home/pirj/source/rspec-rails/tmp/spec/generator/posts_generator_spec.rb" to exist but it does not respond to either `exist?` or `exists?`
 ```

Most certainly, we just need to clean this up in rspec-rails specs and use `Pathname` as you suggest.
